Taghelper/Taghelper/Models/Book.cs
namespace Taghelper.Models
{
    public class Book
    {
        public int BookID { set; get; }
        public String Title { set; get; }
        public float Cost { set; get; }
        public String AuthorName { set; get; }
    }
}

Taghelper/Taghelper/Models/ErrorViewModel.cs
namespace Taghelper.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Taghelper/Taghelper/Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;

namespace Taghelper.Controllers
{
    public class CalcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public int Add(int x,int y) 
        {
            return x + y;
        }
    }
}

Taghelper/Taghelper/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using Taghelper.Models;

namespace Taghelper.Controllers
{
    public class HomeController : Controller
    {
		private readonly IConfiguration _configuration;
		private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger,IConfiguration configuration)
        {
           _configuration= configuration;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(int x,IFormCollection Collection)
        
        { StringBuilder data = new StringBuilder(500);
            data.Append(" x:");
            data.Append(x);
            data.Append(" ");
            data.Append("name:");
            data.Append(Collection["name"]);
            data.Append(" ");
            data.Append("Password:");
            data.Append(Collection["Password"]);

            ViewData["x"] = data.ToString();
            return View("IndexPost");

        }
        public IActionResult DoTask(int? id)
        {
            if (id.HasValue)
            {
                ViewData["id"]=id.Value;
            }
            else
            {
                ViewData["id"] = 0;
            }
            return View();

        }
        public IActionResult GetBook()
        {
            Book b1 = new Book() { AuthorName = "H Lee" };
            ViewData["book"]=b1;    
            return View();
        }
        [ResponseCache(Duration = 15)]
        public IActionResult GetTime()
        {
            string todate = DateTime.Now.ToLongTimeString();
            ViewData["date"] = todate;
            return View();
        }

        public IActionResult Menu()
        {
            String ConString = _configuration.GetConnectionString("DefaultConnection");
            _logger.Log(LogLevel.Information, ConString );
            return View();
        }
		public IActionResult Echo(String name,String city)
		{
            String s1 = "User" + name + "from City=" + city;
            ViewData.Add("Data1", s1);
            return View();
		}
		public IActionResult SayHello(String name)
		{
            String s1 = ("Hello" + name);
            ViewData.Add("Data1" , s1);

            return View(Echo);
		}


		public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Taghelper/Taghelper/Controllers/PartialviewController.cs
using Microsoft.AspNetCore.Mvc;

namespace Taghelper.Controllers
{
    public class PartialviewController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Tabs()
        {
            ViewData["data1"] = "Tom and Jerry are Good friends";
            return View();
        }
    }
}

Taghelper/Taghelper/Controllers/VishnuController.cs
using Microsoft.AspNetCore.Mvc;

namespace Taghelper.Controllers
{
	public class VishnuController : Controller
	{
		//Get:
		public IActionResult Start()
		{
			return View();
		}
	}
}

Taghelper/Taghelper/Views/Partialview/ChildList.cshtml
@{
    ViewData["Title"] = "ChildList";
}

<h1>ChildList</h1>
<div style="background-color: cyan">
    <hr />
    <h1>From Child View</h1>
    <ul>
        <li>Benz</li>
        <li>Innova</li>
        <li>Tesla M3</li>
    </ul>
    <hr />
</div>

Taghelper/Taghelper/Views/Partialview/ChildViewdata.cshtml
<div style="background-color: purple">
	<h1>From ChildViewdata View:@ViewData["data1"]</h1>
</div>

Taghelper/Taghelper/Views/Partialview/Index.cshtml
<div>
	@{
		var all_route_parms = new Dictionary<string, string>
		{
			{"x","200"} ,{"y","50"}
		};
	}
</div>
<div>
	<a asp-action="Add" asp-controller="Calc" asp-route-x="258" asp-route-y="6">CallAdd asp-route</a>

</div>
<div>
	<a asp-action="Add" asp-controller="Calc" asp-all-route-data="all_route_parms">CallAdd all_route_parms</a>
</div>

Taghelper/Taghelper/Views/Partialview/MyView.cshtml
<hr />
<h1>Andhaman Beaches List</h1>
<ul>
	<li>RadhaNagar</li>
	<li>Neal Island</li>
	<li>Ross Island</li>
	<li>Wandoor</li>
</ul>
<hr />

Taghelper/Taghelper/Views/Partialview/Score.cshtml
<div class="text-center">
	<h1>Score</h1>
	<h3>256 for 4 in 20 Overs</h3>
</div>

Taghelper/Taghelper/Views/Partialview/Tabs.cshtml
@{
    ViewData["Title"] = "Tabs";
}

<h1>Tabs</h1>
<div>
    <ul id="tabsstrip" class="nav nav-tabs" role="tablist">
        <li class="active">
            <a href="#_FirstTab" role="tab" data-toggle="tab">Submission</a>
        </li>
        <li>
            <a href="#_SecondTab" role="tab" data-toggle="tab">Search</a>
        </li>
        <li>
            <a href="#_ThirdTab" role="tab" data-toggle="tab">Comments</a>
        </li>
    </ul>
     <div class="tab-pane fade in active" id="_FirstTab">
         <partial name="Score"/>
     </div>
    <div class="tab-pane fade in active" id="_SecondTab">
        <partial name="ChildList" />
    </div>
    <div class="tab-pane fade in active" id="_ThirdTab">
        <partial name="ChildViewdata" view-data="ViewData" />
    </div>
     
</div>
<partial name="Score" />
<partial name="ChildList" />
<partial name="ChildViewdata" view-data="ViewData" />

Taghelper/Taghelper/Views/Shared/_BookList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<hr />
<h1>From Book List</h1>
<ul>
    <li>Wasted in Engineering</li>
    <li>It Happens For a Reason</li>
    <li>The leader In You</li>
    <li>The One Minute Manager</li>
</ul>

Taghelper/Taghelper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Taghelper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Taghelper.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Taghelper</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Taghelper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Taghelper/Taghelper/Views/Shared/_MovieList.cshtml
@{
    ViewData["Title"] = "_MovieList";
}

<h1>_MovieList</h1>
<ul>
    <li>SpiderMan</li>
    <li>SuperMan</li>
    <li>BatMan</li>
</ul>